language: go

services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?$/

before_install:
  - docker pull jboss/keycloak
  - docker run -d -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=secret -e KEYCLOAK_IMPORT=/tmp/gocloak-realm.json -v `pwd`/testdata/gocloak-realm.json:/tmp/gocloak-realm.json -p 8080:8080 --name keycloak jboss/keycloak
  - docker ps

after_failure:
  - docker logs keycloak

script:
  - go test -cover -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
