language: go

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker pull jboss/keycloak
  - docker run -d -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=secret -e KEYCLOAK_IMPORT=/tmp/gocloak-realm.json -v `pwd`/testdata/gocloak-realm.json:/tmp/gocloak-realm.json -p 8080:8080 --name keycloak jboss/keycloak
  - docker ps

after_failure:
  - docker logs keycloak

script:
  - go test -cover -v -race
