name: Tests
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        env:
          GOROOT: /go
        run: |
          docker pull golangci/golangci-lint:latest-alpine
          docker run --rm -v ${PWD}:/app -w /app golangci/golangci-lint:latest-alpine golangci-lint run
      - name: nancy
        uses: sonatype-nexus-community/nancy-github-action@master
        with:
          target: go.sum
      - name: Run Keycloak
        run: |
          docker pull jboss/keycloak:latest
          docker run -d -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=secret -e KEYCLOAK_IMPORT=/tmp/gocloak-realm.json -v "`pwd`/testdata/gocloak-realm.json:/tmp/gocloak-realm.json" -p 8080:8080 --name keycloak jboss/keycloak:latest -Dkeycloak.profile.feature.upload_scripts=enabled
          sleep 10
      - name: Unit Tests
        run: |
          go test -race -cover -coverprofile=coverage.txt -covermode=atomic -cpu 1,2 -bench . -benchmem > test.log
          cat test.log
      - name: Failed Logs
        if: failure()
        run: |
          cat test.log
          docker ps
          docker logs keycloak
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

      # Publish benchmarks for the master branch only
      - name: Store Benchmark Result
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: rhysd/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: "go"
          # Where the output from the benchmark tool is stored
          output-file-path: test.log
          # Push and deploy GitHub pages branch automatically
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

      # Updating go repord card for master branch only
      - name: GoReportCard
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: curl --fail --request POST "https://goreportcard.com/checks" --data "repo=github.com/Nerzal/gocloak"
